version: '3.8'

services:
  app:
    build:
      context: ./AluguelDeMotos
      dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=postgres;Username=user;Password=password;"
    depends_on:
      - database
      - rabbitmq
    restart: always

  consumidor:
    build:
      context: ./Consumidor
      dockerfile: ./Dockerfile
    depends_on:
      - database
      - rabbitmq
    command: ["dotnet", "ConsoleProject.dll"]

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: